version: '3.9'

services:
  app:
    build:
      context: .
    container_name: auth-service
    env_file:
      - .env
    ports:
      - 8000:8000
    command: sh -c "uvicorn src.main:app --host=0.0.0.0 --port=8000"
    depends_on:
      - db

  migrations:
    build: .
    container_name: migrations-tool
    command: sh -c "alembic upgrade head"
    depends_on:
      - db
    env_file:
      - .env
    profiles:
      - tools

  db:
    container_name: users-db
    image: postgres:15
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432


volumes:
  pgdbdata:

networks:
  default:
    external:
      name: agronetwork